[project]
name = "ava"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "google-generativeai>=0.8.5",
    "load-dotenv>=0.1.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
